### ISSUE TITLE
Proposal to use new System Log API and some other changes

### ISSUE THREAD

**Issue by jordansissel** [SecurityRiskAdvisors/logstash-input-okta_enterprise#1]
Hello! I have some ideas I would like to run by you for this plugin:

1. Update it to use the newer [System Logs](https://developer.okta.com/docs/api/resources/system_log) API (The Events API is deprecated). This will likely be a breaking change as the API docs claim that System Logs and Events have different JSON schemas.
2. Recommend removing `auth_token_file` in favor of either environment variables or the [secrets keystore](https://www.elastic.co/guide/en/logstash/current/keystore.html)
3. Change unsuccessful http responses to log them instead of creating events.
4. Hardcode the url path (`/api/v1/logs`) and have a setting just for the domain

For all of these changes, I am planning to code them. I would like your feedback on the above, any guidance you wish to provide, and whether or not you would accept patches for any or all of the above.

(I saw your request  to [move this plugin into logstash-plugins](https://github.com/elastic/logstash/issues/8412), and we can address that at the same time as the work I propose)

**Comment by p-b--** [comment]
Thanks for stopping by! I had some reasons for the decisions made when initially writing the plugin.

1. Agreed, my plan was always to use the System Logs API, however, most orgs I spoke with were unwilling to upgrade to the beta version of Okta on their org to expose the API. Let me see if it's possible to access this API via the GA version of Okta. Would it be sufficient to create another version of the plugin to parse the System Logs API which could get added?

2. I also support `auth_token_env` so people can use an environment variable get the `auth_token` into the application. I am a **huge** fan of the keystore! It wasn't there when I first developed this and in fact I was looking at the kernel keystore at the time.

3. I modeled failure off `http_poller` (https://github.com/logstash-plugins/logstash-input-http_poller/blob/master/lib/logstash/inputs/http_poller.rb#L201) where you send http failures as events as opposed to just logging due to the fact that people don't like mysterious errors. I agreed with that philosophy and implemented it accordingly. I highlight Okta errors accordingly due to the fact that I wanted them to be clear in the loggers that people were using on the far side.

4. I'll reach out to Okta support again, at the time they had said customers can get custom endpoints for things. I do see the need for having just the domain to reduce complexity however. How would you feel about making another input option of `domain` which people normally use, and an option of `url` which is only set for advanced cases? It can be an error to have both `domain` and `url` set at the same time.

Regarding making the changes, I am happy to make them or if you'd like to make a PR and submit, I'd be happy to review. Please let me know what you'd prefer.

We can talk about integration into the logstash-plugins dir as well depending on you view of the code maturity.

I was also curious about the tests written for the project, I did try and mimic what you had for http_poller, with additions for features specific to this project.

**Comment by jordansissel** [comment]
Ahh, good idea :)

**Comment by jordansissel** [comment]
okta_system_log sounds appropriate and easy to find when searching. +1

**Comment by p-b--** [comment]
Great -- I'll spin one up. Thanks!

**Comment by p-b--** [comment]
Closing this ticket based on the release of https://github.com/SecurityRiskAdvisors/logstash-input-okta_system_log.

@jordansissel -- I'll open an issue on the logstash-plugins project, let me know if there is anything more you'd like done on that plugin.
