### ISSUE TITLE
Consider Lowering logging level 

### ISSUE THREAD

**Issue by csanders-git** [SecurityRiskAdvisors/logstash-input-okta_enterprise#2]
Great plugin, nice work.

Looking at the logs we see that on info level we get a message every scheduled fire. https://github.com/SecurityRiskAdvisors/logstash-input-okta_enterprise/blob/master/lib/logstash/inputs/okta_enterprise.rb#L462

I think this is a bit heavy. As I am not typically seeing much on the info level from other plugins. My thought is that this should be a debug and a warn if the status code is not 200. Thoughts?

**Comment by p-b--** [comment]
Hey -- thanks for the note.

I had initially made that info in the case that there was a failure, you would be able to identify the last successful pull in the logs.

Upon review, I can see the value in dropping that to debug, however I want to make sure that I'm OK with success logging only being available in debug, and that too with the full header and body which would be a bit much.

Let me see what the options are -- and then I'll update accordingly.

**Comment by p-b--** [comment]
OK, so I've thought about this and I wanted to drop the route I'm going to go so you know.

I am concerned about the lack of INFO level logging to help folks mark where in the stream they are, since most people have logging at an INFO level, moving it to debug will remove that entirely.

I'm going to add a modulus value, so you will be able to choose how often to generate the message. I realize it's adding arbitrary complexity, but it retains backwards compatibility 

I'll be adding a field `noisy_logging_mod` which will take an integer value for a modulus to write for that log line (and others I feel are very noisy).

Essentially the code will look like this:
```
if counter % noisy_logging_mod == 0
{
  logger.info("....")
  counter++
}
```
So if you need to cut down logging, you will be able to do so using that value. This retains backwards compatibility, at least until I update for the next version.

**Comment by csanders-git** [comment]
I think that's a reasonable solution. Thanks for thinking it through. Let me know if you'd like help writing or (more likely) testing.

**Comment by p-b--** [comment]
I've added the fix, I ended up naming it `log_throttle`, however the functionality is as I described.

You should see it on RubyGems shortly.

**Comment by p-b--** [comment]
@csanders-git  -- just as a heads up, we've released a new plugin [here](https://github.com/SecurityRiskAdvisors/logstash-input-okta_system_log) which pulls from the Okta System Log instead of the the Events API.
